---

- hosts: tag_Name_BastionHost
  become: yes
  tasks:
  - name: installing apache server
    yum:
      name: httpd
      state: present
  - name: making index.html file in /var/www/html directory
    file:
      state: touch
      path: /var/www/html/index.html
  - name: adding the content in index.html
    shell: echo "This is a custom website" > /var/www/html/index.html
  - name: starting the apache server
    service:
      name: httpd
      state: restarted
