---

- hosts: ec2
  become: yes
  tasks:
  - name: installing apache server
    yum:
      name: httpd
      state: absent
  - name: making index.html file in /var/www/html directory
    file:
      state: touch
      path: /var/www/html/index.html
  - name: adding the content in index.html
    shell: echo "THis is my custom website" > /var/www/html/index.html

  - name: changing the text
    lineinfile:
      regexp: ^THis is my custom website
      dest: /var/www/html/index.html
      insertafter: ^#website
      line: "This is my custom webiste for {{ ansible_hostname }}"
  - name: starting the apache server
    service:
      name: httpd
      state: restarted
