---
- hosts: tag_Name_nyk_prod_react
  tasks:
   - debug: msg="The server hostname is {{ ansible_hostname }}"
   - debug: msg="The OS version for {{ ansible_hostname }} is {{ ansible_distribution }}:{{ ansible_distribution_major_version }}"
